# Generated by Django 5.0.4 on 2024-04-04 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2024, 4, 4, 4, 34, 59, 954516, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
